[tool.poetry]
name = "lindera"
version = "0.34.1"
description = ""
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
maturin = "^1.7.1"
patchelf = "^0.17.2.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
black = "^24.10.0"
isort = "^5.13.2"
autopep8 = "^2.3.1"
flake8 = "^7.1.1"
flake8-pyproject = "^1.2.3"
mypy = "^1.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
